Week 5, Assignment C1:

Logistic Regression with Yahoo! Finance API in Python

In this notebook, we will study Logistic Regression using the Yahoo! Finance API in Python.

Please complete the lines bellow where you see "#TODO".

do this first
in the anaconda prompt  or in the Google Colab

pip install pandas-datareader
pip install yfinance

In [1]:
!pip install yfinance

In [2]:
#Objective 1.
#Use this cell to import the Numpy (as np), Pandas (as pd), and YFinance (as yf) packages.
import datetime as dt
import numpy as np 
import pandas as pd
import yfinance as yf

#Our work will also require some components of the Sklearn and Pandas_Datareader packages as imported below:

from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split

from sklearn.model_selection import cross_val_score
from pandas_datareader import data as pdr
yf.pdr_override()

In [3]:
#Objective 2.
#Select a stock symbol for a stock whose historical data is available on the Yahoo! Finance website.  Store the
#string of your chosen symbol to the new variable "stock_symbol".
start = dt.datetime(2020,1,1)
end = dt.datetime.now()

stock_symbol = ['DOGE-USD']

In [4]:
#Objective 3.
#Use the function "pdr.get_data_yahoo(stock_symbol, start_date, end_date)" to generate a Pandas dataframe of
#historical stock data for your chosen stock.  Retain only the first four columns of the dataframe.  Be sure to 
#drop any rows containing NaN's, and take a peek at the resulting dataframe to make sure everything looks good.
deletd_column =[]
df = pdr.get_data_yahoo(stock_symbol, start, end).dropna()
df = df[["Open","Adj Close"]]

#df.head()

[*********************100%***********************]  1 of 1 completed


In [5]:
#Objective 4.
#Use the historical data to define some predictor variables.  Add these variables to the dataframe.  Include, at a
#minimum, (Predictor.I) the rolling average closing price over the past fifteen (15) days and (Predictor.II) the
#change in opening price over the past one (1) day.  Be sure to again drop any rows containing NaN's, and take a
#peek at the resulting dataframe to make sure everything looks good.  Store the dataframe as the new variable "X".

df['Close_15_Rolling'] = df['Adj Close'].rolling(window=15).mean() 
df['Open_1_Change'] = df['Open'].shift(1)
df=df.dropna()
X=df
X

Open  Adj Close  Close_15_Rolling  Open_1_Change
Date                                                            
2020-01-15  0.002468   0.002369          0.002303       0.002358
2020-01-16  0.002372   0.002345          0.002323       0.002468
2020-01-17  0.002346   0.002490          0.002356       0.002372
2020-01-18  0.002490   0.002507          0.002380       0.002346
2020-01-19  0.002514   0.002405          0.002391       0.002490
...              ...        ...               ...            ...
2021-11-06  0.261264   0.261898          0.268313       0.263655
2021-11-07  0.261971   0.266315          0.269285       0.261264
2021-11-08  0.266728   0.282359          0.269639       0.261971
2021-11-09  0.282539   0.273526          0.270227       0.266728
2021-11-10  0.274031   0.270110          0.271186       0.282539

[662 rows x 4 columns]

In [6]:
#Objective 5.
#Define the target or dependent variable to be one (1) if the change in closing price over the past one (1) day is
#nonnegative and negative one (-1) if the change in closing price over the past one (1) day is negative.  This
#variable's values should be forward-looking (i.e., you should subtract today's price from tomorrow's price rather
#than subtracting yesterday's price from today's price).  Store the resulting values as the new variable "y".  You
#may find the "np.where(*args)" function to be useful.  Look it up in Numpy documentation for support.
#np.where(a < 5, a, 10*a)
y = np.where(df["Adj Close"].shift(-1) - df["Adj Close"] >= 0, 1, -1)
y

array([-1,  1,  1, -1, -1,  1, -1, -1,  1, -1,  1,  1,  1, -1,  1, -1,  1,
        1, -1,  1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1, -1, -1, -1,  1,
       -1,  1, -1, -1,  1, -1, -1, -1, -1, -1, -1,  1,  1,  1, -1,  1, -1,
       -1, -1,  1, -1, -1, -1,  1, -1,  1, -1,  1, -1,  1,  1,  1, -1,  1,
        1, -1,  1, -1, -1, -1,  1, -1,  1,  1, -1,  1, -1,  1,  1,  1,  1,
       -1,  1,  1, -1,  1, -1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1, -1,
       -1,  1, -1,  1,  1, -1, -1,  1,  1,  1, -1, -1, -1, -1,  1,  1,  1,
       -1,  1,  1,  1, -1, -1, -1,  1,  1, -1,  1, -1,  1,  1,  1,  1, -1,
        1, -1,  1,  1, -1, -1,  1, -1, -1,  1, -1,  1,  1, -1, -1,  1, -1,
       -1, -1,  1,  1,  1,  1, -1, -1, -1, -1,  1, -1,  1,  1,  1, -1, -1,
        1,  1,  1,  1, -1, -1,  1, -1, -1,  1, -1, -1,  1,  1, -1, -1,  1,
       -1,  1, -1,  1,  1, -1,  1, -1,  1, -1,  1, -1,  1,  1, -1,  1, -1,
       -1, -1,  1, -1,  1,  1,  1, -1, -1,  1, -1, -1,  1, -1,  1, -1,  1,
       -1, -1, -1,  1,  1

In [7]:
#Objective 6.
#Split the data into training and test sets, putting the first seventy percent (70%) of the data in the training
#set.

#y_data = X["Adj Close_Change"] 
#x_data = X.drop("Adj Close_Change", axis = 1)


index = int(0.7*len(X))
X_train,X_test,y_train,y_test = X[:index], X[index:], y[:index], y[index:]


In [8]:
#Objective 7.
#Instantiate the Logistic Regression model object, and use its ".fit(*args)" method to fit the model to the 
#training data.
logistic = LogisticRegression()
logistic = logistic.fit(X_train,y_train)



In [9]:
#Objective 8.
#Examine the model's coefficients by using its ".coef_" method.

pd.DataFrame(zip(X.columns, np.transpose(logistic.coef_)))

0                       1
0              Open      [-0.2605769360409]
1         Adj Close   [-0.3565487361464747]
2  Close_15_Rolling  [-0.24997749258199864]
3     Open_1_Change   [-0.2760831545767646]

In [10]:
#Objective 9.
#Use the model's ".predict_proba(*args)" and ".predict(*args)" methods to generate predictions over the test set.

probabilities = logistic.predict_proba(X_test)
predictions = logistic.predict(X_test)
print(probabilities)
print(predictions)

[[0.55123128 0.44876872]
 [0.55222941 0.44777059]
 [0.5591402  0.4408598 ]
 [0.56159688 0.43840312]
 [0.56734433 0.43265567]
 [0.5731425  0.4268575 ]
 [0.57766477 0.42233523]
 [0.58634004 0.41365996]
 [0.59848515 0.40151485]
 [0.62009573 0.37990427]
 [0.62808758 0.37191242]
 [0.64137748 0.35862252]
 [0.64073948 0.35926052]
 [0.6401048  0.3598952 ]
 [0.6235692  0.3764308 ]
 [0.61663482 0.38336518]
 [0.602614   0.397386  ]
 [0.60874967 0.39125033]
 [0.61483216 0.38516784]
 [0.62180504 0.37819496]
 [0.62440152 0.37559848]
 [0.61955348 0.38044652]
 [0.61742961 0.38257039]
 [0.60208328 0.39791672]
 [0.59695194 0.40304806]
 [0.58707013 0.41292987]
 [0.5862695  0.4137305 ]
 [0.57829137 0.42170863]
 [0.57914772 0.42085228]
 [0.57835895 0.42164105]
 [0.58116964 0.41883036]
 [0.57828159 0.42171841]
 [0.57487623 0.42512377]
 [0.57036616 0.42963384]
 [0.56740232 0.43259768]
 [0.56805647 0.43194353]
 [0.57289308 0.42710692]
 [0.58175182 0.41824818]
 [0.58636581 0.41363419]
 [0.58636495 0.41363505]


In [11]:
#Objective 10.
#Use the function "metrics.confusion_matrix(*args)" to create a confusion matrix comparing the predicted and true
#classification labels over the test set.

confusion_matrix =metrics.confusion_matrix(y_test,predictions)
confusion_matrix



array([[104,   0],
       [ 95,   0]])

In [12]:
#Objective 11.
#Calculate the model's accuracy on the test set using its ".score(*args)" method.
from sklearn.metrics import accuracy_score 
accuracy = accuracy_score(y_test,predictions)
accuracy


0.5226130653266332

In [13]:
#Objective 12.
#Use five-fold cross validation to cross-check the accuracy of the model over different held-out test sets.  This
#is where you should use the function "cross_val_score(*args)".

cross_val = cross_val_score(logistic,X, y, cv=5)
print(cross_val)
print(cross_val.mean())

[0.5037594  0.5037594  0.50757576 0.59848485 0.49242424]
0.5212007290954659
